---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-swift-proxy
    - memcached
    - python-swiftclient
    - python-keystone-auth-token
  tags: swift-proxy

- shell: sed -i 's/OPTIONS=.*/OPTIONS="-l {{ PROXY_LOCAL_NET_IP }}"/g' /etc/sysconfig/memcached && touch ~/.executed-swift-proxy-01 creates=~/.executed-swift-proxy-01
  tags: swift-proxy

- service: name=memcached state=running enabled=yes
  tags: swift-proxy

- shell: cat /vagrant/provisioning/roles/proxy/files/proxy-server.conf | sed 's/SWIFT_PASS/{{ swift_pass }}/g' | sudo tee /etc/swift/proxy-server.conf && touch ~/.executed-swift-proxy-02 creates=~/.executed-swift-proxy-02
  tags: swift-proxy

- shell: mkdir -p /etc/swift/keystone-signing && chown -R swift:swift /etc/swift/keystone-signing && touch ~/.executed-swift-proxy-03 creates=~/.executed-swift-proxy-03
  tags: swift-proxy
- shell: swift-ring-builder account.builder create 18 3 1 && swift-ring-builder container.builder create 18 3 1 && swift-ring-builder object.builder create 18 3 1 && touch ~/.executed-swift-proxy-04 creates=~/.executed-swift-proxy-04 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder account.builder add z{{ ZONE }}-{{ STORAGE_LOCAL_NET_IP }}:6002R{{ STORAGE_REPLICATION_NET_IP }}:6005/{{ DEVICE }} 100 && touch ~/.executed-swift-proxy-05 creates=~/.executed-swift-proxy-05 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder container.builder add z{{ ZONE }}-{{ STORAGE_LOCAL_NET_IP_1 }}:6001R{{ STORAGE_REPLICATION_NET_IP }}:6004/{{ DEVICE }} 100 && touch ~/.executed-swift-proxy-06 creates=~/.executed-swift-proxy-06 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder object.builder add z{{ ZONE }}-{{ STORAGE_LOCAL_NET_IP_1 }}:6000R{{ STORAGE_REPLICATION_NET_IP }}:6003/{{ DEVICE }} 100 && touch ~/.executed-swift-proxy-07 creates=~/.executed-swift-proxy-07 chdir=/etc/swift
  tags: swift-proxy

- shell: swift-ring-builder account.builder && touch ~/.executed-swift-proxy-08 creates=~/.executed-swift-proxy-08 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder container.builder && touch ~/.executed-swift-proxy-09 creates=~/.executed-swift-proxy-09 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder object.builder && touch ~/.executed-swift-proxy-10 creates=~/.executed-swift-proxy-10 chdir=/etc/swift
  tags: swift-proxy

- shell: swift-ring-builder account.builder rebalance && touch ~/.executed-swift-proxy-11 creates=~/.executed-swift-proxy-11 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder container.builder rebalance && touch ~/.executed-swift-proxy-12 creates=~/.executed-swift-proxy-12 chdir=/etc/swift
  tags: swift-proxy
- shell: swift-ring-builder object.builder rebalance && touch ~/.executed-swift-proxy-13 creates=~/.executed-swift-proxy-13 chdir=/etc/swift
  tags: swift-proxy

- shell: chown -R swift:swift /etc/swift && touch ~/.executed-swift-proxy-14 creates=~/.executed-swift-proxy-14
  tags: swift-proxy


- service: name={{ item }} state=running enabled=yes
  with_items: 
    - openstack-swift-proxy
  tags: swift-proxy

