---
- shell: yum groupinstall -y "Japanese Support" && touch ~/.executed-japanese-1 creates=~/.executed-japanese-1
  tags: japanese

- shell: localedef -f UTF-8 -i ja_JP ja_JP.utf8 && touch ~/.executed-japanese-2 creates=~/.executed-japanese-2
  tags: japanese

- shell: sed -i 's/^/#/g' /etc/sysconfig/i18n && touch ~/.executed-japanese-3 creates=~/.executed-japanese-3
  tags: japanese

- shell: echo 'LANG="ja_JP.UTF-8"' | sudo tee -a /etc/sysconfig/i18n && touch ~/.executed-japanese-4 creates=~/.executed-japanese-4
  tags: japanese

- shell: echo 'SYSFONT="latarcyrheb-sun16"' | sudo tee -a /etc/sysconfig/i18n && touch ~/.executed-japanese-5 creates=~/.executed-japanese-5
  tags: japanese

- shell: cp /usr/share/zoneinfo/Japan /etc/localtime && touch ~/.executed-japanese-6 creates=~/.executed-japanese-6
  tags: japanese

- shell: sed -i 's/^ZONE/#ZONE/g' /etc/sysconfig/clock && touch ~/.executed-japanese-7 creates=~/.executed-japanese-7
  tags: japanese

- shell: echo 'ZONE="Asia/Tokyo"' | sudo tee -a /etc/sysconfig/clock && touch ~/.executed-japanese-8 creates=~/.executed-japanese-8
  tags: japanese