---
- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-openstack-01", command: "cat /vagrant/provisioning/roles/common/files/hosts | sudo tee -a /etc/hosts" }
  tags: openstack

- yum: name={{ item }} state=present
  with_items:
    - "http://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-3.noarch.rpm"
  tags: openstack

- yum: name={{ item }} state=present
  with_items:
    - "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
  tags: openstack

- yum: name={{ item }} state=installed
  with_items:
    - openstack-utils
    - openstack-selinux
    - python-keystoneclient
    - MySQL-python
    - ntp
  tags: openstack

- yum: name=* state=latest
  tags: openstack

- service: name=ntpd state=running enabled=yes
  tags: openstack