---
- shell: pvcreate /dev/sdb && touch ~/.executed-cinder-block-19 creates=~/.executed-cinder-block-19
  tags: cinder
- shell: vgcreate cinder-volumes /dev/sdb && touch ~/.executed-cinder-block-20 creates=~/.executed-cinder-block-20
  tags: cinder
- shell: sed -i 's_^    filter =.*_filter = [ "a/sda1/", "a/sdb/", "r/.*/"]_g' /etc/lvm/lvm.conf && touch ~/.executed-cinder-block-1 creates=~/.executed-cinder-block-1
  tags: cinder

- yum: name={{ item }} state=installed
  with_items:
    - openstack-cinder
    - scsi-target-utils
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT auth_strategy keystone && touch ~/.executed-cinder-block-2 creates=~/.executed-cinder-block-2
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-cinder-block-3 creates=~/.executed-cinder-block-3
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_host controller && touch ~/.executed-cinder-block-4 creates=~/.executed-cinder-block-4
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_protocol http && touch ~/.executed-cinder-block-5 creates=~/.executed-cinder-block-5
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_port 35357 && touch ~/.executed-cinder-block-6 creates=~/.executed-cinder-block-6
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_user cinder && touch ~/.executed-cinder-block-7 creates=~/.executed-cinder-block-7
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-cinder-block-8 creates=~/.executed-cinder-block-8
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_password {{ cinder_pass }} && touch ~/.executed-cinder-block-9 creates=~/.executed-cinder-block-9
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT rpc_backend cinder.openstack.common.rpc.impl_qpid && touch ~/.executed-cinder-block-10 creates=~/.executed-cinder-block-10
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT qpid_hostname controller && touch ~/.executed-cinder-block-11 creates=~/.executed-cinder-block-11
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf database connection mysql://cinder:{{ cinder_dbpass }}@controller/cinder && touch ~/.executed-cinder-block-12 creates=~/.executed-cinder-block-12
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT glance_host controller && touch ~/.executed-cinder-block-13 creates=~/.executed-cinder-block-13
  tags: cinder

- shell: echo 'include /etc/cinder/volumes/*' | sudo tee -a /etc/tgt/targets.conf && touch ~/.executed-cinder-block-14 creates=~/.executed-cinder-block-14


- service: name={{ item }} state=running enabled=yes
  with_items:
    - openstack-cinder-volume
    - tgtd
  tags: cinder
