---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-cinder
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf database connection mysql://cinder:{{ cinder_dbpass }}@controller/cinder && touch ~/.executed-cinder-1 creates=~/.executed-cinder-1
  tags: cinder

- shell: cinder-manage db sync && touch ~/.executed-cinder-2 creates=~/.executed-cinder-2
  tags: cinder

- shell: keystone user-create --name=cinder --pass={{ cinder_pass }} --email=cinder@example.com && touch ~/.executed-cinder-3 creates=~/.executed-cinder-3
  environment: admin_openrc
  tags: cinder
- shell: keystone user-role-add --user=cinder --tenant=service --role=admin && touch ~/.executed-cinder-4 creates=~/.executed-cinder-4
  environment: admin_openrc
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT auth_strategy keystone && touch ~/.executed-cinder-5 creates=~/.executed-cinder-5
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-cinder-6 creates=~/.executed-cinder-6
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_host controller && touch ~/.executed-cinder-7 creates=~/.executed-cinder-7
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_protocol http && touch ~/.executed-cinder-8 creates=~/.executed-cinder-8
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken auth_port 35357 && touch ~/.executed-cinder-9 creates=~/.executed-cinder-9
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_user cinder && touch ~/.executed-cinder-10 creates=~/.executed-cinder-10
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-cinder-11 creates=~/.executed-cinder-11
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf keystone_authtoken admin_password {{ cinder_pass }} && touch ~/.executed-cinder-12 creates=~/.executed-cinder-12
  tags: cinder

- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT rpc_backend cinder.openstack.common.rpc.impl_qpid && touch ~/.executed-cinder-13 creates=~/.executed-cinder-13
  tags: cinder
- shell: openstack-config --set /etc/cinder/cinder.conf DEFAULT qpid_hostname controller && touch ~/.executed-cinder-14 creates=~/.executed-cinder-14
  tags: cinder

- shell: keystone service-create --name=cinder --type=volume --description="OpenStack Block Storage" && touch ~/.executed-cinder-15 creates=~/.executed-cinder-15
  environment: admin_openrc
  tags: cinder
- shell: keystone endpoint-create --service-id=$(keystone service-list | awk '/ volume / {print $2}') --publicurl=http://controller:8776/v1/%\(tenant_id\)s --internalurl=http://controller:8776/v1/%\(tenant_id\)s --adminurl=http://controller:8776/v1/%\(tenant_id\)s && touch ~/.executed-cinder-16 creates=~/.executed-cinder-16
  environment: admin_openrc
  tags: cinder

- shell: keystone service-create --name=cinderv2 --type=volumev2 --description="OpenStack Block Storage v2" && touch ~/.executed-cinder-17 creates=~/.executed-cinder-17
  environment: admin_openrc
  tags: cinder
- shell: keystone endpoint-create --service-id=$(keystone service-list | awk '/ volumev2 / {print $2}') --publicurl=http://controller:8776/v2/%\(tenant_id\)s --internalurl=http://controller:8776/v2/%\(tenant_id\)s --adminurl=http://controller:8776/v2/%\(tenant_id\)s && touch ~/.executed-cinder-18 creates=~/.executed-cinder-18
  environment: admin_openrc
  tags: cinder

- service: name={{ item }} state=running enabled=yes
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  tags: cinder

