---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-cinder
  tags: cinder

- shell: openstack-config --set {{ item.target }} {{ item.group }} {{ item.key }} {{ item.value }} && touch {{ item.index }} creates={{ item.index }}
  with_items:
    - { index: "~/.executed-cinder-01", group: "database", key: "connection", value: "mysql://cinder:{{ CINDER_DBPASS }}@controller/cinder", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-02", group: "DEFAULT", key: "auth_strategy", value: "keystone", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-03", group: "keystone_authtoken", key: "auth_uri", value: "http://controller:5000", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-04", group: "keystone_authtoken", key: "auth_host", value: "controller", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-05", group: "keystone_authtoken", key: "auth_protocol", value: "http", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-06", group: "keystone_authtoken", key: "auth_port", value: "35357", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-07", group: "keystone_authtoken", key: "admin_user", value: "cinder", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-08", group: "keystone_authtoken", key: "admin_tenant_name", value: "service", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-09", group: "keystone_authtoken", key: "admin_password", value: "{{ CINDER_PASS }}", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-10", group: "DEFAULT", key: "rpc_backend", value: "cinder.openstack.common.rpc.impl_qpid", target: "/etc/cinder/cinder.conf"}
    - { index: "~/.executed-cinder-11", group: "DEFAULT", key: "qpid_hostname", value: "controller", target: "/etc/cinder/cinder.conf"}
  tags: cinder

- shell: cinder-manage db sync && touch ~/.executed-cinder-12 creates=~/.executed-cinder-12
  tags: cinder

- service: name={{ item }} state=running enabled=yes
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  tags: cinder

