---
- name: Create database openstack
  mysql_db: db={{ item }} state=present encoding=utf8
  with_items:
    - keystone
    - glance
    - nova
    - neutron
    - dash
    - cinder
    - heat
  tags: database

- name: Create database user keystone
  mysql_user: >
    name=keystone
    password="{{ keystone_dbpass }}"
    priv=keystone.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database

- name: Create database user glance
  mysql_user: >
    name=glance
    password="{{ glance_dbpass }}"
    priv=glance.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database

- name: Create database user nova
  mysql_user: >
    name=nova
    password="{{ nova_dbpass }}"
    priv=nova.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database

- name: Create database user neutron
  mysql_user: >
    name=neutron
    password="{{ neutron_dbpass }}"
    priv=neutron.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database

- name: Create database user dash
  mysql_user: >
    name=dash
    password="{{ dash_dbpass }}"
    priv=dash.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database

- name: Create database user cinder
  mysql_user: >
    name=cinder
    password="{{ cinder_dbpass }}"
    priv=cinder.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database

- name: Create database user heat
  mysql_user: >
    name=heat
    password="{{ heat_dbpass }}"
    priv=heat.*:ALL
    host={{ item }}
    state=present
  with_items:
    - "%"
    - localhost
    - controller
  tags: database
