---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-glance
    - python-glanceclient
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf database connection mysql://glance:{{ glance_dbpass }}@controller/glance && touch ~/.executed-glance-1 creates=~/.executed-glance-1
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf database connection mysql://glance:{{ glance_dbpass }}@controller/glance && touch ~/.executed-glance-2 creates=~/.executed-glance-2
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf DEFAULT rpc_backend qpid && touch ~/.executed-glance-3 creates=~/.executed-glance-3
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf DEFAULT qpid_hostname controller && touch ~/.executed-glance-4 creates=~/.executed-glance-4
  tags: glance

- shell: glance-manage db_sync && touch ~/.executed-glance-5 creates=~/.executed-glance-5
  tags: glance

- shell: keystone user-create --name=glance --pass={{ glance_pass }} --email=glance@example.com && touch ~/.executed-glance-6 creates=~/.executed-glance-6
  environment: admin_openrc
  tags: glance

- shell: keystone user-role-add --user=glance --tenant=service --role=admin && touch ~/.executed-glance-7 creates=~/.executed-glance-7
  environment: admin_openrc
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-glance-8 creates=~/.executed-glance-8
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_host controller && touch ~/.executed-glance-9 creates=~/.executed-glance-9
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_port 35357 && touch ~/.executed-glance-10 creates=~/.executed-glance-10
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_protocol http && touch ~/.executed-glance-11 creates=~/.executed-glance-11
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-glance-12 creates=~/.executed-glance-12
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_user glance && touch ~/.executed-glance-13 creates=~/.executed-glance-13
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf keystone_authtoken admin_password {{ glance_pass }} && touch ~/.executed-glance-14 creates=~/.executed-glance-14
  tags: glance

- shell: openstack-config --set /etc/glance/glance-api.conf paste_deploy flavor keystone && touch ~/.executed-glance-15 creates=~/.executed-glance-15
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-glance-16 creates=~/.executed-glance-16
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_host controller && touch ~/.executed-glance-17 creates=~/.executed-glance-17
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_port 35357 && touch ~/.executed-glance-18 creates=~/.executed-glance-18
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_protocol http && touch ~/.executed-glance-19 creates=~/.executed-glance-19
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-glance-20 creates=~/.executed-glance-20
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_user glance && touch ~/.executed-glance-21 creates=~/.executed-glance-21
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken admin_password {{ glance_pass }} && touch ~/.executed-glance-22 creates=~/.executed-glance-22
  tags: glance

- shell: openstack-config --set /etc/glance/glance-registry.conf paste_deploy flavor keystone && touch ~/.executed-glance-23 creates=~/.executed-glance-23
  tags: glance

- shell: keystone service-create --name=glance --type=image --description="OpenStack Image Service" && touch ~/.executed-glance-24 creates=~/.executed-glance-24
  environment: admin_openrc
  tags: glance

- shell: keystone endpoint-create --service-id=$(keystone service-list | awk '/ image / {print $2}') --publicurl=http://controller:9292 --internalurl=http://controller:9292 --adminurl=http://controller:9292 && touch ~/.executed-glance-25 creates=~/.executed-glance-25
  environment: admin_openrc
  tags: glance

- shell: chown -R glance:glance /var/lib/glance/ && sudo chown -R glance:glance /etc/glance && sudo chown -R glance:glance /var/log/glance && touch ~/.executed-glance-26 creates=~/.executed-glance-26
  tags: glance

- service: name=openstack-glance-api state=running enabled=yes
  tags: glance

- service: name=openstack-glance-registry state=running enabled=yes
  tags: glance

# - get_url: url="http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img" dest=/vagrant/tmp
#   tags: glance

- shell: glance image-create --name "cirros-0.3.2-x86_64" --disk-format qcow2 --container-format bare --is-public True --progress < /vagrant/tmp/cirros-0.3.2-x86_64-disk.img && touch ~/.executed-glance-27 creates=~/.executed-glance-27
  environment: admin_openrc
  tags: glance

