---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-glance
    - python-glanceclient
  tags: glance

- shell: openstack-config --set {{ item.target }} {{ item.group }} {{ item.key }} {{ item.value }} && touch {{ item.index }} creates={{ item.index }}
  with_items:  
    - { index: "~/.executed-glance-01", group: "database", key: "connection", value: "mysql://glance:{{ GLANCE_DBPASS }}@controller/glance", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-02", group: "database", key: "connection", value: "mysql://glance:{{ GLANCE_DBPASS }}@controller/glance", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-03", group: "DEFAULT", key: "rpc_backend", value: "qpid", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-04", group: "DEFAULT", key: "qpid_hostname", value: "controller", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-05", group: "keystone_authtoken", key: "auth_uri", value: "http://controller:5000", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-06", group: "keystone_authtoken", key: "auth_host", value: "controller", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-07", group: "keystone_authtoken", key: "auth_port", value: "35357", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-08", group: "keystone_authtoken", key: "auth_protocol", value: "http", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-09", group: "keystone_authtoken", key: "admin_tenant_name", value: "service", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-10", group: "keystone_authtoken", key: "admin_user", value: "glance", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-11", group: "keystone_authtoken", key: "admin_password", value: "{{ GLANCE_PASS }}", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-12", group: "paste_deploy", key: "flavor", value: "keystone", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-13", group: "keystone_authtoken", key: "auth_uri", value: "http://controller:5000", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-14", group: "keystone_authtoken", key: "auth_host", value: "controller", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-15", group: "keystone_authtoken", key: "auth_port", value: "35357", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-16", group: "keystone_authtoken", key: "auth_protocol", value: "http", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-17", group: "keystone_authtoken", key: "admin_tenant_name", value: "service", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-18", group: "keystone_authtoken", key: "admin_user", value: "glance", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-19", group: "keystone_authtoken", key: "admin_password", value: "{{ GLANCE_PASS }}", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-20", group: "paste_deploy", key: "flavor", value: "keystone", target: "/etc/glance/glance-registry.conf"}
    - { index: "~/.executed-glance-21", group: "DEFAULT", key: "notification_driver", value: "messaging", target: "/etc/glance/glance-api.conf"}
    - { index: "~/.executed-glance-22", group: "DEFAULT", key: "rpc_backend", value: "qpid", target: "/etc/glance/glance-api.conf"}
  tags: glance

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-glance-23", command: "glance-manage db_sync" }
    - { index: "~/.executed-glance-24", command: "chown -R glance:glance /var/lib/glance" }
    - { index: "~/.executed-glance-25", command: "chown -R glance:glance /etc/glance" }
    - { index: "~/.executed-glance-26", command: "chown -R glance:glance /var/log/glance" }
  tags: glance

- service: name={{ item }} state=running enabled=yes
  with_items:
    - openstack-glance-api
    - openstack-glance-registry
  tags: glance

# - get_url: url="http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img" dest=/vagrant/tmp
#   tags: glance

# - shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
#   with_items:
#     - { index: "~/.executed-glance-27", command: "glance image-create --name \"cirros-0.3.2-x86_64\" --disk-format qcow2 --container-format bare --is-public True --progress < /vagrant/tmp/cirros-0.3.2-x86_64-disk.img" }
#   environment: admin_openrc
#   tags: glance
