---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-keystone
  tags: keystone

- shell: openstack-config --set {{ item.target }} {{ item.group }} {{ item.key }} {{ item.value }} && touch {{ item.index }} creates={{ item.index }}
  with_items:
    - { index: "~/.executed-keystone-controller-01", group: "database", key: "connection", value: "mysql://keystone:{{ KEYSTONE_DBPASS }}@controller/keystone", target: "/etc/keystone/keystone.conf"}
    - { index: "~/.executed-keystone-controller-02", group: "sql", key: "connection", value: "mysql://keystone:{{ KEYSTONE_DBPASS }}@controller/keystone", target: "/etc/keystone/keystone.conf"}
    - { index: "~/.executed-keystone-controller-03", group: "DEFAULT", key: "admin_token", value: "{{ ADMIN_TOKEN }}", target: "/etc/keystone/keystone.conf"}
  tags: keystone

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-keystone-controller-04", command: "keystone-manage db_sync" }
    - { index: "~/.executed-keystone-controller-05", command: "keystone-manage pki_setup --keystone-user keystone --keystone-group keystone" }
    - { index: "~/.executed-keystone-controller-06", command: "chown -R keystone:keystone /etc/keystone/ssl" }
    - { index: "~/.executed-keystone-controller-07", command: "chown -R keystone:keystone /var/log/keystone" }
    - { index: "~/.executed-keystone-controller-08", command: "chmod -R o-rwx /etc/keystone/ssl" }
  tags: keystone

- service: name=openstack-keystone state=running enabled=yes
  tags: keystone

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-keystone-controller-09", command: "(sudo crontab -l 2>&1 | grep -q token_flush) || echo '@hourly /usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1' | sudo tee -a /var/spool/cron/root" }
    - { index: "~/.executed-keystone-controller-10", command: "cat /vagrant/provisioning/roles/controller/files/keystonerc | sed 's/$KEYSTONE_USERNAME/admin/g' | sed 's/$KEYSTONE_PASSWORD/{{ ADMIN_PASS }}/g' | sudo tee keystonerc_admin" }
    - { index: "~/.executed-keystone-controller-11", command: "cat /vagrant/provisioning/roles/controller/files/keystonerc | sed 's/$KEYSTONE_USERNAME/demo/g' | sed 's/$KEYSTONE_PASSWORD/{{ DEMO_PASS }}/g' | sudo tee keystonerc_demo" }
  tags: keystone

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-keystone-configure-01", command: "keystone user-create --name=admin --pass={{ ADMIN_PASS }} --email={{ ADMIN_EMAIL }}" }
    - { index: "~/.executed-keystone-configure-02", command: "keystone role-create --name=admin" }
    - { index: "~/.executed-keystone-configure-03", command: "keystone tenant-create --name=admin --description=\"Admin Tenant\"" }
    - { index: "~/.executed-keystone-configure-04", command: "keystone user-role-add --user=admin --tenant=admin --role=admin" }
    - { index: "~/.executed-keystone-configure-05", command: "keystone user-role-add --user=admin --role=_member_ --tenant=admin" }
    - { index: "~/.executed-keystone-configure-06", command: "keystone user-create --name=demo --pass={{ DEMO_PASS }} --email={{ DEMO_EMAIL }}" }
    - { index: "~/.executed-keystone-configure-07", command: "keystone tenant-create --name=demo --description=\"Demo Tenant\"" }
    - { index: "~/.executed-keystone-configure-08", command: "keystone user-role-add --user=demo --role=_member_ --tenant=demo" }
    - { index: "~/.executed-keystone-configure-09", command: "keystone tenant-create --name=service --description=\"Service Tenant\"" }
    - { index: "~/.executed-keystone-configure-10", command: "keystone service-create --name=keystone --type=identity --description=\"OpenStack Identity\"" }
    - { index: "~/.executed-keystone-configure-11", command: "keystone endpoint-create --service-id=$(keystone service-list | awk '/ identity / {print $2}') --publicurl=http://controller:5000/v2.0 --internalurl=http://controller:5000/v2.0 --adminurl=http://controller:35357/v2.0" }
  environment: service_token
  tags: keystone-configure

- shell: keystone role-create --name={{ item.role }} && touch {{ item.index }} creates={{ item.index }}
  with_items: keystone_roles
  environment: admin_openrc
  tags: keystone-configure

- shell: keystone user-create --name={{ item.name }} --pass={{ item.password }} --email={{ item.email }} && touch {{ item.index }} creates={{ item.index }}
  with_items: keystone_users
  environment: admin_openrc
  tags: keystone-configure

- shell: keystone user-role-add --user={{ item.user }} --tenant=service --role={{ item.role }} && touch {{ item.index }} creates={{ item.index }}
  with_items: keystone_user_roles
  environment: admin_openrc
  tags: keystone-configure

- shell: keystone service-create --name={{ item.name }} --type={{ item.type }} --description='{{ item.description }}' && touch {{ item.index }} creates={{ item.index }}
  with_items: keystone_services
  environment: admin_openrc
  tags: keystone-configure

- shell: keystone endpoint-create --service-id=$(keystone service-list | awk '/ {{ item.type }} / {print $2}') --publicurl='{{ item.public }}' --adminurl='{{ item.admin }}' --internalurl='{{ item.internal }}' && touch {{ item.index }} creates={{ item.index }}
  with_items: keystone_endpoints
  environment: admin_openrc
  tags: keystone-configure
