---
- shell: neutron net-create ext-net --shared --router:external=True && touch ~/.executed-network-1 creates=~/.executed-network-1
  environment: admin_openrc
  tags: network
- shell: neutron subnet-create ext-net --name ext-subnet --allocation-pool start={{ FLOATING_IP_START }},end={{ FLOATING_IP_END }} --disable-dhcp --gateway {{ EXTERNAL_NETWORK_GATEWAY }} {{ EXTERNAL_NETWORK_CIDR }} && touch ~/.executed-network-2 creates=~/.executed-network-2
  environment: admin_openrc
  tags: network

- shell: neutron net-create demo-net && touch ~/.executed-network-3 creates=~/.executed-network-3
  environment: demo_openrc
  tags: network
- shell: neutron subnet-create demo-net --name demo-subnet --gateway {{ TENANT_NETWORK_GATEWAY }} {{ TENANT_NETWORK_CIDR }} && touch ~/.executed-network-4 creates=~/.executed-network-4
  environment: demo_openrc
  tags: network
- shell: neutron router-create demo-router && touch ~/.executed-network-4.5 creates=~/.executed-network-4.5
  environment: demo_openrc
  tags: network
- shell: neutron router-interface-add demo-router demo-subnet && touch ~/.executed-network-5 creates=~/.executed-network-5
  environment: demo_openrc
  tags: network
- shell: neutron router-gateway-set demo-router ext-net && touch ~/.executed-network-6 creates=~/.executed-network-6
  environment: demo_openrc
  tags: network

