
- shell: keystone user-create --name=neutron --pass={{ neutron_pass }} --email=neutron@example.com && touch ~/.executed-neutron-1 creates=~/.executed-neutron-1
  environment: admin_openrc
  tags: neutron
- shell: keystone user-role-add --user neutron --tenant service --role admin && touch ~/.executed-neutron-2 creates=~/.executed-neutron-2
  environment: admin_openrc
  tags: neutron
- shell: keystone service-create --name neutron --type network --description "OpenStack Networking" && touch ~/.executed-neutron-3 creates=~/.executed-neutron-3
  environment: admin_openrc
  tags: neutron
- shell: keystone endpoint-create --service-id $(keystone service-list | awk '/ network / {print $2}') --publicurl http://controller:9696 --adminurl http://controller:9696 --internalurl http://controller:9696 && touch ~/.executed-neutron-4 creates=~/.executed-neutron-4
  environment: admin_openrc
  tags: neutron

- yum: name={{ item }} state=installed
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - python-neutronclient
  tags: neutron

- shell: openstack-config --set /etc/neutron/neutron.conf database connection mysql://neutron:{{ neutron_dbpass }}@controller/neutron && touch ~/.executed-neutron-5 creates=~/.executed-neutron-5
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone && touch ~/.executed-neutron-6 creates=~/.executed-neutron-6
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-neutron-7 creates=~/.executed-neutron-7
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_host controller && touch ~/.executed-neutron-8 creates=~/.executed-neutron-8
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_protocol http && touch ~/.executed-neutron-9 creates=~/.executed-neutron-9
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_port 35357 && touch ~/.executed-neutron-10 creates=~/.executed-neutron-10
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-neutron-11 creates=~/.executed-neutron-11
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron && touch ~/.executed-neutron-12 creates=~/.executed-neutron-12
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_password {{ neutron_pass }} && touch ~/.executed-neutron-13 creates=~/.executed-neutron-13
  tags: neutron

- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT rpc_backend neutron.openstack.common.rpc.impl_qpid && touch ~/.executed-neutron-14 creates=~/.executed-neutron-14
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT qpid_hostname controller && touch ~/.executed-neutron-15 creates=~/.executed-neutron-15
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_status_changes True && touch ~/.executed-neutron-16 creates=~/.executed-neutron-16
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_data_changes True && touch ~/.executed-neutron-17 creates=~/.executed-neutron-17
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_url http://controller:8774/v2 && touch ~/.executed-neutron-18 creates=~/.executed-neutron-18
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_username nova && touch ~/.executed-neutron-19 creates=~/.executed-neutron-19
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_tenant_id $(keystone tenant-list | awk '/ service / { print $2 }') && touch ~/.executed-neutron-20 creates=~/.executed-neutron-20
  environment: admin_openrc
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_password {{ nova_pass }} && touch ~/.executed-neutron-21 creates=~/.executed-neutron-21
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_auth_url http://controller:35357/v2.0 && touch ~/.executed-neutron-22 creates=~/.executed-neutron-22
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT core_plugin ml2 && touch ~/.executed-neutron-23 creates=~/.executed-neutron-23
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT service_plugins router && touch ~/.executed-neutron-24 creates=~/.executed-neutron-24
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT verbose True && touch ~/.executed-neutron-24.5 creates=~/.executed-neutron-24.5
  tags: neutron
- shell: sed -i 's/^service_provider=/#service_provider=/g' /etc/neutron/neutron.conf && touch ~/.executed-neutron-24.6 creates=~/.executed-neutron-24.6
  tags: neutron

- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers gre && touch ~/.executed-neutron-25 creates=~/.executed-neutron-25
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types gre && touch ~/.executed-neutron-26 creates=~/.executed-neutron-26
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch && touch ~/.executed-neutron-27 creates=~/.executed-neutron-27
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 1:1000 && touch ~/.executed-neutron-28 creates=~/.executed-neutron-28
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver && touch ~/.executed-neutron-29 creates=~/.executed-neutron-29
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True && touch ~/.executed-neutron-30 creates=~/.executed-neutron-30
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API && touch ~/.executed-neutron-31 creates=~/.executed-neutron-31
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_url http://controller:9696 && touch ~/.executed-neutron-32 creates=~/.executed-neutron-32
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_auth_strategy keystone && touch ~/.executed-neutron-33 creates=~/.executed-neutron-33
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_tenant_name service && touch ~/.executed-neutron-34 creates=~/.executed-neutron-34
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_username neutron && touch ~/.executed-neutron-35 creates=~/.executed-neutron-35
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_password {{ neutron_pass }} && touch ~/.executed-neutron-36 creates=~/.executed-neutron-36
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_auth_url http://controller:35357/v2.0 && touch ~/.executed-neutron-37 creates=~/.executed-neutron-37
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver && touch ~/.executed-neutron-38 creates=~/.executed-neutron-38
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver && touch ~/.executed-neutron-39 creates=~/.executed-neutron-39
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT security_group_api neutron && touch ~/.executed-neutron-40 creates=~/.executed-neutron-40
  tags: neutron
- shell: ln -s plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini && touch ~/.executed-neutron-41 creates=~/.executed-neutron-41
  tags: neutron

- service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  tags: neutron
- service: name={{ item }} state=running enabled=yes
  with_items:
    - neutron-server
  tags: neutron

- shell: openstack-config --set /etc/nova/nova.conf DEFAULT service_neutron_metadata_proxy true && touch ~/.executed-neutron-42 creates=~/.executed-neutron-42
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_metadata_proxy_shared_secret {{ metadata_secret }} && touch ~/.executed-neutron-42 creates=~/.executed-neutron-42
  tags: neutron

- service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
  tags: neutron

