---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - python-novaclient
  tags: nova

- shell: openstack-config --set {{ item.target }} {{ item.group }} {{ item.key }} {{ item.value }} && touch {{ item.index }} creates={{ item.index }}
  with_items:
    - { index: "~/.executed-nova-01", group: "database", key: "connection", value: "mysql://nova:{{ NOVA_DBPASS }}@controller/nova", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-02", group: "DEFAULT", key: "rpc_backend", value: "qpid", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-03", group: "DEFAULT", key: "qpid_hostname", value: "controller", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-04", group: "DEFAULT", key: "my_ip", value: "10.0.0.11", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-05", group: "DEFAULT", key: "vncserver_listen", value: "10.0.0.11", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-06", group: "DEFAULT", key: "vncserver_proxyclient_address", value: "10.0.0.11", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-07", group: "DEFAULT", key: "vnc_keymap", value: "ja", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-08", group: "DEFAULT", key: "auth_strategy", value: "keystone", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-09", group: "keystone_authtoken", key: "auth_uri", value: "http://controller:5000", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-10", group: "keystone_authtoken", key: "auth_host", value: "controller", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-11", group: "keystone_authtoken", key: "auth_protocol", value: "http", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-12", group: "keystone_authtoken", key: "auth_port", value: "35357", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-13", group: "keystone_authtoken", key: "admin_user", value: "nova", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-14", group: "keystone_authtoken", key: "admin_tenant_name", value: "service", target: "/etc/nova/nova.conf"}
    - { index: "~/.executed-nova-15", group: "keystone_authtoken", key: "admin_password", value: "{{ NOVA_PASS }}", target: "/etc/nova/nova.conf"}
  tags: nova

- shell: nova-manage db sync && touch ~/.executed-nova-6.2 creates=~/.executed-nova-6.2
  tags: nova

- service: name={{ item }} state=running enabled=yes
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
  tags: nova
