---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-console
    - openstack-nova-novncproxy
    - openstack-nova-scheduler
    - python-novaclient
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf database connection mysql://nova:{{ nova_dbpass }}@controller/nova && touch ~/.executed-nova-1 creates=~/.executed-nova-1
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend qpid && touch ~/.executed-nova-2 creates=~/.executed-nova-2
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT qpid_hostname controller && touch ~/.executed-nova-3 creates=~/.executed-nova-3
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT my_ip 10.0.0.11 && touch ~/.executed-nova-4 creates=~/.executed-nova-4
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_listen 10.0.0.11 && touch ~/.executed-nova-5 creates=~/.executed-nova-5
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address 10.0.0.11 && touch ~/.executed-nova-6 creates=~/.executed-nova-6
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT vnc_keymap ja && touch ~/.executed-nova-6.1 creates=~/.executed-nova-6.1
  tags: nova
- shell: nova-manage db sync && touch ~/.executed-nova-6.2 creates=~/.executed-nova-6.2
  tags: nova

- shell: keystone user-create --name=nova --pass={{ nova_pass }} --email=nova@example.com && touch ~/.executed-nova-7 creates=~/.executed-nova-7
  environment: admin_openrc
  tags: nova
- shell: keystone user-role-add --user=nova --tenant=service --role=admin && touch ~/.executed-nova-8 creates=~/.executed-nova-8
  environment: admin_openrc
  tags: nova

- shell: openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone && touch ~/.executed-nova-9 creates=~/.executed-nova-9
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-nova-10 creates=~/.executed-nova-10
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_host controller && touch ~/.executed-nova-11 creates=~/.executed-nova-11
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_protocol http && touch ~/.executed-nova-12 creates=~/.executed-nova-12
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_port 35357 && touch ~/.executed-nova-13 creates=~/.executed-nova-13
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_user nova && touch ~/.executed-nova-14 creates=~/.executed-nova-14
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-nova-15 creates=~/.executed-nova-15
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_password {{ nova_pass }} && touch ~/.executed-nova-16 creates=~/.executed-nova-16
  tags: nova

- shell: keystone service-create --name=nova --type=compute --description="OpenStack Compute" && touch ~/.executed-nova-17 creates=~/.executed-nova-17
  environment: admin_openrc
  tags: nova
- shell: keystone endpoint-create --service-id=$(keystone service-list | awk '/ compute / {print $2}') --publicurl=http://controller:8774/v2/%\(tenant_id\)s --internalurl=http://controller:8774/v2/%\(tenant_id\)s --adminurl=http://controller:8774/v2/%\(tenant_id\)s && touch ~/.executed-nova-18 creates=~/.executed-nova-18
  environment: admin_openrc
  tags: nova

- service: name=openstack-nova-api state=running enabled=yes
  tags: nova
- service: name=openstack-nova-cert state=running enabled=yes
  tags: nova
- service: name=openstack-nova-consoleauth state=running enabled=yes
  tags: nova
- service: name=openstack-nova-scheduler state=running enabled=yes
  tags: nova
- service: name=openstack-nova-conductor state=running enabled=yes
  tags: nova
- service: name=openstack-nova-novncproxy state=running enabled=yes
  tags: nova
