---
- yum: name={{ item }} state=installed
  with_items:
    - mysql
    - mysql-server
    - qpid-cpp-server
  tags: mysql-server

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-mysql-server-01", command: "cat /vagrant/provisioning/roles/controller/files/my.cnf | sudo tee -a /etc/my.cnf" }
    - { index: "~/.executed-mysql-server-02", command: "sed -i 's/^auth=/#auth=/g' /etc/qpidd.conf" }
    - { index: "~/.executed-mysql-server-03", command: "echo 'auth=no' | sudo tee -a /etc/qpidd.conf" }
  tags: mysql-server

- service: name={{ item }} state=running enabled=yes
  with_items:
    - mysqld
    - qpidd
  tags: mysql-server

- mysql_db: db={{ item.name }} state=present encoding=utf8
  with_items: database_users
  tags: database

- mysql_user: name={{ item.name }} password="{{ item.password }}" priv={{ item.name }}.*:ALL host={{ item.host }} state=present
  with_items: database_users
  tags: database
