---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-ceilometer-api
    - openstack-ceilometer-collector
    - openstack-ceilometer-notification
    - openstack-ceilometer-central
    - openstack-ceilometer-alarm
    - python-ceilometerclient
  tags: ceilometer


- yum: name={{ item }} state=installed
  with_items:
    - mongodb-server
    - mongodb
  tags: ceilometer

- shell: sed -i 's/^bind_ip =.*/bind_ip = 10.0.0.11/g' /etc/mongodb.conf && touch ~/.executed-ceilometer-00 creates=~/.executed-ceilometer-00

- service: name={{ item }} state=running enabled=yes
  with_items: 
    - mongodb
  tags: ceilometer

- shell: mongo --host controller --eval ' db = db.getSiblingDB("ceilometer"); db.addUser({user: "ceilometer", pwd: "{{ CEILOMETER_DBPASS }}", roles: [ "readWrite", "dbAdmin" ]})' && touch ~/.executed-ceilometer-01 creates=~/.executed-ceilometer-01

- shell: openstack-config --set /etc/ceilometer/ceilometer.conf publisher metering_secret {{ CEILOMETER_TOKEN }} && touch ~/.executed-ceilometer-02 creates=~/.executed-ceilometer-02

- shell: openstack-config --set /etc/ceilometer/ceilometer.conf DEFAULT rpc_backend ceilometer.openstack.common.rpc.impl_qpid && touch ~/.executed-ceilometer-03 creates=~/.executed-ceilometer-03

- shell: keystone user-create --name=ceilometer --pass={{ CEILOMETER_PASS }} -- email=ceilometer@example.com && touch ~/.executed-ceilometer-04 creates=~/.executed-ceilometer-04
  environment: admin_openrc
- shell: keystone user-role-add --user=ceilometer --tenant=service --role=admin && touch ~/.executed-ceilometer-05 creates=~/.executed-ceilometer-05
  environment: admin_openrc

- shell: openstack-config --set /etc/ceilometer/ceilometer.conf DEFAULT auth_strategy keystone && touch ~/.executed-ceilometer-06 creates=~/.executed-ceilometer-06


- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken auth_host controller && touch ~/.executed-ceilometer-07 creates=~/.executed-ceilometer-07
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken admin_user ceilometer && touch ~/.executed-ceilometer-08 creates=~/.executed-ceilometer-08
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-ceilometer-09 creates=~/.executed-ceilometer-09
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken auth_protocol http && touch ~/.executed-ceilometer-10 creates=~/.executed-ceilometer-10
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-ceilometer-11 creates=~/.executed-ceilometer-11
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken admin_password {{ CEILOMETER_PASS }} && touch ~/.executed-ceilometer-12 creates=~/.executed-ceilometer-12
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_auth_url http://controller:5000/v2.0 && touch ~/.executed-ceilometer-13 creates=~/.executed-ceilometer-13
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_username ceilometer && touch ~/.executed-ceilometer-14 creates=~/.executed-ceilometer-14
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_tenant_name service && touch ~/.executed-ceilometer-15 creates=~/.executed-ceilometer-15
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_password {{ CEILOMETER_PASS }} && touch ~/.executed-ceilometer-16 creates=~/.executed-ceilometer-16

- shell: keystone service-create --name=ceilometer --type=metering --description="Telemetry" && touch ~/.executed-ceilometer-17 creates=~/.executed-ceilometer-17
  environment: admin_openrc
- shell: keystone endpoint-create --service-id=$(keystone service-list | awk '/ metering / {print $2}') --publicurl=http://controller:8777 --internalurl=http://controller:8777 --adminurl=http://controller:8777 && touch ~/.executed-ceilometer-18 creates=~/.executed-ceilometer-18
  environment: admin_openrc

- service: name={{ item }} state=running enabled=yes
  with_items: 
    - openstack-ceilometer-api
    - openstack-ceilometer-notification
    - openstack-ceilometer-central
    - openstack-ceilometer-collector
    - openstack-ceilometer-alarm-evaluator
    - openstack-ceilometer-alarm-notifier
