---
- yum: name={{ item }} state=installed
  with_items:
    - mysql
    - mysql-server
    - qpid-cpp-server
  tags: server

- copy: src=my.cnf dest=/tmp/my.cnf
  tags: server

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed-server-01", command: "cat /tmp/my.cnf | sudo tee -a /etc/my.cnf" }
    - { index: "~/.executed-server-02", command: "sed -i 's/^auth=/#auth=/g' /etc/qpidd.conf" }
    - { index: "~/.executed-server-03", command: "echo 'auth=no' | sudo tee -a /etc/qpidd.conf" }
  tags: server

- service: name={{ item }} state=running enabled=yes
  with_items:
    - mysqld
    - qpidd
  tags: server

- mysql_db: db={{ item.name }} state=present encoding=utf8
  with_items: DATABASE_USERS
  tags: server

- mysql_user: name={{ item.name }} password="{{ item.password }}" priv={{ item.name }}.*:ALL host={{ item.host }} state=present
  with_items: DATABASE_USERS
  tags: server
