---
- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed/cinder-volume-01", command: "pvcreate /dev/sdb" }
    - { index: "~/.executed/cinder-volume-02", command: "vgcreate cinder-volumes /dev/sdb" }
    - { index: "~/.executed/cinder-volume-03", command: "sed -i 's_^    filter =.*_filter = [ \"a/sda1/\", \"a/sdb/\", \"r/.*/\"]_g' /etc/lvm/lvm.conf" }
  tags: cinder-volume

- yum: name={{ item }} state=installed
  with_items:
    - openstack-cinder
    - scsi-target-utils
  tags: cinder-volume

- shell: openstack-config --set {{ item.target }} {{ item.group }} {{ item.key }} {{ item.value }} && touch {{ item.index }} creates={{ item.index }}
  with_items:
    - { index: "~/.executed/cinder-volume-11", group: "database", key: "connection", value: "mysql://cinder:{{ CINDER_DBPASS }}@controller/cinder", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-12", group: "DEFAULT", key: "auth_strategy", value: "keystone", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-13", group: "DEFAULT", key: "rpc_backend", value: "cinder.openstack.common.rpc.impl_qpid", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-14", group: "DEFAULT", key: "qpid_hostname", value: "controller", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-15", group: "DEFAULT", key: "glance_host", value: "controller", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-16", group: "DEFAULT", key: "control_exchange", value: "cinder", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-17", group: "DEFAULT", key: "notification_driver", value: "cinder.openstack.common.notifier.rpc_notifier", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-18", group: "keystone_authtoken", key: "auth_uri", value: "http://controller:5000", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-19", group: "keystone_authtoken", key: "identity_uri", value: "http://controller:35357", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-20", group: "keystone_authtoken", key: "admin_user", value: "cinder", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-21", group: "keystone_authtoken", key: "admin_tenant_name", value: "service", target: "/etc/cinder/cinder.conf" }
    - { index: "~/.executed/cinder-volume-22", group: "keystone_authtoken", key: "admin_password", value: "{{ CINDER_PASS }}", target: "/etc/cinder/cinder.conf" }
  tags: cinder-volume

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed/cinder-volume-31", command: "echo 'include /etc/cinder/volumes/*' | sudo tee -a /etc/tgt/targets.conf" }
  tags: cinder-volume

- service: name={{ item }} state=running enabled=yes
  with_items:
    - openstack-cinder-volume
    - tgtd
  tags: cinder-volume

