---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-ceilometer-compute
    - python-ceilometerclient
    - python-pecan
  tags: ceilometer-compute

- shell: openstack-config --set /etc/nova/nova.conf DEFAULT instance_usage_audit True
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT instance_usage_audit_period hour
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT notify_on_state_change vm_and_task_state

#section:
#Edit the /etc/nova/nova.conf file and add the following lines to the [DEFAULT]
#[DEFAULT]
#...
#notification_driver = nova.openstack.common.notifier.rpc_notifier
#notification_driver = ceilometer.compute.nova_notifier
#- shell: openstack-config --set /etc/nova/nova.conf DEFAULT auth_host controller
#- shell: openstack-config --set /etc/nova/nova.conf DEFAULT auth_host controller

# service openstack-nova-compute restart

- shell: openstack-config --set /etc/ceilometer/ceilometer.conf publisher metering_secret {{ CEILOMETER_TOKEN }}

- shell: openstack-config --set /etc/ceilometer/ceilometer.conf DEFAULT qpid_hostname controller

- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken auth_host controller
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken admin_user ceilometer
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken admin_tenant_name service
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken auth_protocol http
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf keystone_authtoken admin_password {{ CEILOMETER_PASS }}
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_username ceilometer
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_tenant_name service
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_password {{ CEILOMETER_PASS }}
- shell: openstack-config --set /etc/ceilometer/ceilometer.conf service_credentials os_auth_url http://controller:5000/v2.0
