---
- shell: cp /etc/sysctl.conf /etc/sysctl.conf.orig && touch ~/.executed-neutron-0 creates=~/.executed-neutron-0
  tags: neutron
- shell: sed -i 's,net.ipv4.conf.all.rp_filter.*,net.ipv4.conf.all.rp_filter=0,g' /etc/sysctl.conf && touch ~/.executed-neutron-1 creates=~/.executed-neutron-1
  tags: neutron
- shell: sed -i 's,net.ipv4.conf.default.rp_filter.*,net.ipv4.conf.default.rp_filter=0,g' /etc/sysctl.conf && touch ~/.executed-neutron-2 creates=~/.executed-neutron-2
  tags: neutron
- shell: sysctl -p && touch ~/.executed-neutron-3 creates=~/.executed-neutron-3
  tags: neutron

- yum: name={{ item }} state=installed
  with_items:
    - openstack-neutron-ml2
    - openstack-neutron-openvswitch
  tags: neutron

- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone && touch ~/.executed-neutron-4 creates=~/.executed-neutron-4
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-neutron-5 creates=~/.executed-neutron-5
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_host controller && touch ~/.executed-neutron-6 creates=~/.executed-neutron-6
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_protocol http && touch ~/.executed-neutron-7 creates=~/.executed-neutron-7
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_port 35357 && touch ~/.executed-neutron-8 creates=~/.executed-neutron-8
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-neutron-9 creates=~/.executed-neutron-9
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron && touch ~/.executed-neutron-10 creates=~/.executed-neutron-10
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_password {{ neutron_pass }} && touch ~/.executed-neutron-11 creates=~/.executed-neutron-11
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT rpc_backend neutron.openstack.common.rpc.impl_qpid && touch ~/.executed-neutron-12 creates=~/.executed-neutron-12
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT qpid_hostname controller && touch ~/.executed-neutron-13 creates=~/.executed-neutron-13
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT core_plugin ml2 && touch ~/.executed-neutron-14 creates=~/.executed-neutron-14
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT service_plugins router && touch ~/.executed-neutron-15 creates=~/.executed-neutron-15
  tags: neutron
- shell: openstack-config --set /etc/neutron/neutron.conf DEFAULT verbose True && touch ~/.executed-neutron-16 creates=~/.executed-neutron-16
  tags: neutron
- shell: sed -i 's/^service_provider=/#service_provider=/g' /etc/neutron/neutron.conf && touch ~/.executed-neutron-16.1 creates=~/.executed-neutron-16.1
  tags: neutron

- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers gre && touch ~/.executed-neutron-17 creates=~/.executed-neutron-17
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types gre && touch ~/.executed-neutron-18 creates=~/.executed-neutron-18
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch && touch ~/.executed-neutron-19 creates=~/.executed-neutron-19
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 1:1000 && touch ~/.executed-neutron-20 creates=~/.executed-neutron-20
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs local_ip {{ instance_tunnels_interface_ip_address }} && touch ~/.executed-neutron-21 creates=~/.executed-neutron-21
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs tunnel_type gre && touch ~/.executed-neutron-22 creates=~/.executed-neutron-22
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs enable_tunneling True && touch ~/.executed-neutron-23 creates=~/.executed-neutron-23
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver && touch ~/.executed-neutron-24 creates=~/.executed-neutron-24
  tags: neutron
- shell: openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True && touch ~/.executed-neutron-25 creates=~/.executed-neutron-25
  tags: neutron

- service: name={{ item }} state=running enabled=yes
  with_items:
    - openvswitch
  tags: neutron

- shell: ovs-vsctl add-br br-int && touch ~/.executed-neutron-26 creates=~/.executed-neutron-26
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API && touch ~/.executed-neutron-27 creates=~/.executed-neutron-27
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_url http://controller:9696 && touch ~/.executed-neutron-28 creates=~/.executed-neutron-28
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_auth_strategy keystone && touch ~/.executed-neutron-29 creates=~/.executed-neutron-29
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_tenant_name service && touch ~/.executed-neutron-30 creates=~/.executed-neutron-30
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_username neutron && touch ~/.executed-neutron-31 creates=~/.executed-neutron-31
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_password {{ neutron_pass }} && touch ~/.executed-neutron-32 creates=~/.executed-neutron-32
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_auth_url http://controller:35357/v2.0 && touch ~/.executed-neutron-33 creates=~/.executed-neutron-33
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver && touch ~/.executed-neutron-34 creates=~/.executed-neutron-34
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver && touch ~/.executed-neutron-35 creates=~/.executed-neutron-35
  tags: neutron
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT security_group_api neutron && touch ~/.executed-neutron-36 creates=~/.executed-neutron-36
  tags: neutron

- shell: ln -s plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini && touch ~/.executed-neutron-37 creates=~/.executed-neutron-37
  tags: neutron
- shell: cp /etc/init.d/neutron-openvswitch-agent /etc/init.d/neutron-openvswitch-agent.orig && touch ~/.executed-neutron-38 creates=~/.executed-neutron-38
  tags: neutron
- shell: sed -i 's,plugins/openvswitch/ovs_neutron_plugin.ini,plugin.ini,g' /etc/init.d/neutron-openvswitch-agent && touch ~/.executed-neutron-39 creates=~/.executed-neutron-39
  tags: neutron

- service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-compute
  tags: neutron

- service: name={{ item }} state=running enabled=yes
  with_items:
    - neutron-openvswitch-agent
  tags: neutron

