---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-nova-compute
  tags: nova

- shell: openstack-config --set /etc/nova/nova.conf database connection mysql://nova:{{ NOVA_DBPASS }}@controller/nova && touch ~/.executed-nova-1 creates=~/.executed-nova-1
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone && touch ~/.executed-nova-2 creates=~/.executed-nova-2
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_uri http://controller:5000 && touch ~/.executed-nova-3 creates=~/.executed-nova-3
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_host controller && touch ~/.executed-nova-4 creates=~/.executed-nova-4
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_protocol http && touch ~/.executed-nova-5 creates=~/.executed-nova-5
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_port 35357 && touch ~/.executed-nova-6 creates=~/.executed-nova-6
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_user nova && touch ~/.executed-nova-7 creates=~/.executed-nova-7
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_tenant_name service && touch ~/.executed-nova-8 creates=~/.executed-nova-8
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf keystone_authtoken admin_password {{ NOVA_PASS }} && touch ~/.executed-nova-9 creates=~/.executed-nova-9
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT rpc_backend qpid && touch ~/.executed-nova-10 creates=~/.executed-nova-10
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT qpid_hostname controller && touch ~/.executed-nova-11 creates=~/.executed-nova-11
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT my_ip 10.0.0.31 && touch ~/.executed-nova-12 creates=~/.executed-nova-12
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT vnc_enabled True && touch ~/.executed-nova-13 creates=~/.executed-nova-13
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_listen 0.0.0.0 && touch ~/.executed-nova-14 creates=~/.executed-nova-14
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address 10.0.0.31 && touch ~/.executed-nova-15 creates=~/.executed-nova-15
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://controller:6080/vnc_auto.html && touch ~/.executed-nova-16 creates=~/.executed-nova-16
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf DEFAULT glance_host controller && touch ~/.executed-nova-17 creates=~/.executed-nova-17
  tags: nova
- shell: openstack-config --set /etc/nova/nova.conf libvirt virt_type qemu && touch ~/.executed-nova-18 creates=~/.executed-nova-18
  tags: nova

- service: name={{ item }} state=running enabled=yes
  with_items:
    - libvirtd
    - messagebus
    - openstack-nova-compute
  tags: nova