---
- yum: name={{ item }} state=installed
  with_items:
    - openstack-nova-compute
  tags: nova

- shell: openstack-config --set {{ item.target }} {{ item.group }} {{ item.key }} {{ item.value }} && touch {{ item.index }} creates={{ item.index }}
  with_items:
    - { index: "~/.executed-nova-01", group: "database", key: "connection", value: "mysql://nova:{{ NOVA_DBPASS }}@controller/nova", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-02", group: "DEFAULT", key: "auth_strategy", value: "keystone", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-03", group: "keystone_authtoken", key: "auth_uri", value: "http://controller:5000", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-04", group: "keystone_authtoken", key: "auth_host", value: "controller", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-05", group: "keystone_authtoken", key: "auth_protocol", value: "http", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-06", group: "keystone_authtoken", key: "auth_port", value: "35357", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-07", group: "keystone_authtoken", key: "admin_user", value: "nova", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-08", group: "keystone_authtoken", key: "admin_tenant_name", value: "service", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-09", group: "keystone_authtoken", key: "admin_password", value: "{{ NOVA_PASS }}", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-10", group: "DEFAULT", key: "rpc_backend", value: "qpid", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-11", group: "DEFAULT", key: "qpid_hostname", value: "controller", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-12", group: "DEFAULT", key: "my_ip", value: "10.0.0.31", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-13", group: "DEFAULT", key: "vnc_enabled", value: "True", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-14", group: "DEFAULT", key: "vncserver_listen", value: "0.0.0.0", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-15", group: "DEFAULT", key: "vncserver_proxyclient_address", value: "10.0.0.31", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-16", group: "DEFAULT", key: "novncproxy_base_url", value: "http://controller:6080/vnc_auto.html", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-17", group: "DEFAULT", key: "glance_host", value: "controller", target: "/etc/nova/nova.conf" }
    - { index: "~/.executed-nova-18", group: "libvirt", key: "virt_type", value: "qemu", target: "/etc/nova/nova.conf" }
  tags: nova

- service: name={{ item }} state=running enabled=yes
  with_items:
    - libvirtd
    - messagebus
    - openstack-nova-compute
  tags: nova