---
#$(openssl rand -hex 10)

KEYSTONE_DBPASS: pass

DEMO_PASS: pass
ADMIN_PASS: pass

GLANCE_DBPASS: pass
GLANCE_PASS: pass
GLANCE_EMAIL: glance@example.com

NOVA_DBPASS: pass
NOVA_PASS: pass
NOVA_EMAIL: nova@example.com

DASH_DBPASS: pass

CINDER_DBPASS: pass
CINDER_PASS: pass
CINDER_EMAIL: cinder@example.com

NEUTRON_DBPASS: pass
NEUTRON_PASS: pass
NEUTRON_EMAIL: neutron@example.com

HEAT_DBPASS: pass
HEAT_PASS: pass
HEAT_EMAIL: heat@example.com

CEILOMETER_DBPASS: pass
CEILOMETER_PASS: pass
CEILOMETER_EMAIL: ceilometer@example.com

TROVE_DBPASS: pass
TROVE_PASS: pass
TROVE_EMAIL: ceilometer@example.com

SWIFT_PASS: pass
SWIFT_EMAIL: swift@example.com

ROOT_DBPASS: pass

ADMIN_TOKEN: cad1c455b5786290bf3e

ADMIN_EMAIL: admin@localhost
DEMO_CREATE: true
DEMO_EMAIL: demo@localhost

METADATA_SECRET: 47f3fd968ed9a176e24b

CEILOMETER_TOKEN: fc1ff2f3620bc3fa8b7a

SERVICE_TOKEN:
  OS_SERVICE_TOKEN: "{{ ADMIN_TOKEN }}"
  OS_SERVICE_ENDPOINT: http://controller:35357/v2.0

ADMIN_OPENRC:
  OS_USERNAME: admin
  OS_PASSWORD: "{{ ADMIN_PASS }}"
  OS_TENANT_NAME: admin
  OS_AUTH_URL: http://controller:35357/v2.0

DEMO_OPENRC:
  OS_USERNAME: demo
  OS_PASSWORD: "{{ DEMO_PASS }}"
  OS_TENANT_NAME: demo
  OS_AUTH_URL: http://controller:35357/v2.0